### ISSUE TITLE
1.2.3 version get methods geting errors

### ISSUE THREAD

**Issue by egarazlic** [brezzhnev/atlassian-connect-core#10]
For the usage with jira there are a  lot of GEt methods that are not using query parameters.
So the calls are being normally without  path?anything
And if we use those calls normally to get results the new JWTHelper have a error in the qsh function
PART:
// Parse a query into the map of parameters
        parse_str($parts['query'], $params);

It is trying to get query parts but there isnt any query parts.

Change:
 $params=array();
 if(isset($parts['query']))
 parse_str($parts['query'], $params);

Could you make change here because a lot of projects are using this so I dont need to update everyone manually

**Comment by brezzhnev** [comment]
Fixed in v1.2.4
