### ISSUE TITLE
Using JWT token auth but also keep the driver session

### ISSUE THREAD

**Issue by libellux** [brezzhnev/atlassian-connect-core#13]
Hello,

First time integrating atlassian connect core testing the jira server service desk. If I already have setup a Laravel auth where users use the driver session guard. How would I implement this package but still keep:

        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

Is there anywhere in the configuration i could change the web array to like:

        'web_atlassian' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],

Hope i made myself clear.

Best regards

**Comment by brezzhnev** [comment]
Basically, JWT token needed to authenticate your tenants, why would you need to keep `session` driver?
