### ISSUE TITLE
Make request to Confluence API

### ISSUE THREAD

**Issue by giorbismiguel** [brezzhnev/atlassian-connect-core#3]
Hello,

How you can do request to the Confluence API?

Thanks

**Comment by brezzhnev** [comment]
Hi @giorbismiguel,

I've almost implemented it. I planning to create release on weekends.

Thanks for your interest!

**Comment by brezzhnev** [comment]
Implemented in `v1.2.0` (8146eb96f65cf849b00ab0ec642fbb20d18b0d2f)

**Comment by giorbismiguel** [comment]
Hi,

Please, can you write an example using JWTClient to get a page in Confluence?
