### ISSUE TITLE
Example using JWTClient

### ISSUE THREAD

**Issue by giorbismiguel** [brezzhnev/atlassian-connect-core#4]
Hi,

Please, can you write an example using JWTClient to get a page in Confluence using the API?

For example, using the following function in the API:
https://developer.atlassian.com/cloud/confluence/rest/#api-content-id-get

Thanks

**Comment by giorbismiguel** [comment]
With the following example, it works :

<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use AtlassianConnectCore\Http\Clients\JWTClient;
use AtlassianConnectCore\Repositories\TenantRepository;

Route::get('/', function () {
    $tenant = new TenantRepository();   
    $jwtClient = new JWTClient($tenant->findById(2));
    $jwtClient->get("/rest/api/user?username=giorbis", ['verify' => false]);
    $result = $jwtClient->get("/rest/api/content/$id/?expand=body.storage&username=$username");
    dd($result); 
});

but when I try:

$tenant = new TenantRepository();
$jwtClient = new JWTClient($tenant->findById(2));
$result = $jwtClient->get("/rest/api/content/$id/?expand=body.storage");
dd($result);

the following error occurs: 

HTTP Status 401 - Expecting claim 'qsh' to have value '9ecd3f3c03a15fee95f24d491835f0df49cde5b228b5973f2389a552272a93da' but instead it has the value '0dfc3b7678f72db73a346852b44f306bbe2df9e44295b9665359a0102a90d6ee'

Status report Expecting claim 'qsh' to have value '9ecd3f3c03a15fee95f24d491835f0df49cde5b228b5973f2389a552272a93da' but instead it has the value '0dfc3b7678f72db73a346852b44f306bbe2df9e44295b9665359a0102a90d6ee'

Description: This request requires HTTP authentication.

**Comment by brezzhnev** [comment]
Hi @giorbismiguel,

Happy new year! Sorry for the delay. 

The method **JWTClient::get()** has the second parameter called `config`. There you should pass your query parameters instead of injecting in URL.

From your example, it should be like this:
``` php
$tenant = app(TenantRepository::class); // actually would be better to use DI in the class constructor
$client = new JWTClient($tenant->findById(2)); // I hope you don't do like this for production :)
$response = $jwtClient->get("/rest/api/content/{$id}", [
    'expand' => 'body.storage'
]);
dd($response);
```

The **config parameter** represents [Guzzle options](http://docs.guzzlephp.org/en/stable/request-options.html).

**Comment by giorbismiguel** [comment]
Thanks, @brezzhnev, it works very well.
