### ISSUE TITLE
When the token expires, how the library manage it?

### ISSUE THREAD

**Issue by giorbismiguel** [brezzhnev/atlassian-connect-core#5]
The library creates the new token or I need to update that manually.

**Comment by brezzhnev** [comment]
Hi @giorbismiguel,

Please, write an exact case of token expiring and ways to reproduce it.

**Comment by brezzhnev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simple task](https://trello.com/c/ITMsH215/1-simple-task)

**Comment by brezzhnev** [comment]
Closed due to inactivity.
