### ISSUE TITLE
Unauthorized (401) 

### ISSUE THREAD

**Issue by DeadMerc** [brezzhnev/atlassian-connect-core#6]
Hi, 
have trouble, with secure request.
I am using 
`$client = new JWTClient(Auth::user());`
`dump($client->post('/rest/api/2/search'.urlencode('?jql=updated > 2014-01-20 and project in (PC) and timespent > 0&fields=summary,worklog&maxResults=1000')));`
I got 401, can you please help me with it? Interesting, what
`dump($client->get('/rest/api/2/issue/TEST-13'));`
works perfectly, problem in jira permissions?

**Comment by brezzhnev** [comment]
Hi @DeadMerc,

That's because you're trying to pass request parameters to URL, you should use the parameter `$config` instead:

``` php
$client = new JWTClient(Auth::user());
$client->post('rest/api/2/search', [
    'query' => [
        'jql' => 'updated > 2014-01-20 and project in (PC) and timespent > 0',
        'fields' => 'summary,worklog',
        'maxResults' => '1000'
    ]
]);
```

You can see all the available options at [Guzzle HTTP documentation](http://docs.guzzlephp.org/en/stable/request-options.html).

Btw, same issue: https://github.com/brezzhnev/atlassian-connect-core/issues/4

**Comment by DeadMerc** [comment]
Thanks for fast response @brezzhnev , but it not working
Your example return 
`Unrecognized field "query" (Class com.atlassian.jira.rest.v2.search.SearchRequestBean), not marked as ignorable`
Tried without query
`Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token`
This request have GET method, it not working too.

**Comment by brezzhnev** [comment]
@DeadMerc when I using GET method it also doesn't work for me, strange.

You could try this, it works for me:
```
$client = new JWTClient(\Auth::user());
$response = $client->post('rest/api/2/search', [
    'jql' => 'updated > 2014-01-20',
    'fields' => ['summary', 'worklog'],
    'maxResults' => '1000'
]);
```

> Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
This error was due to `fields` parameter. When you're performing POST request, you should use an array instead of the string with commas.
