### ISSUE TITLE
Unauthorized exception on GET request (due to space in query parameter value)

### ISSUE THREAD

**Issue by egarazlic** [brezzhnev/atlassian-connect-core#9]
Hi Brezzhnev.
I am trying to to create request to jira api to have users in group provided by name.

$res = $client->get('/rest/api/2/group?groupname=administrators&expand=users');

And this is working normaly.
But when I am trying to get users that are in group that has space in name like one I created.
"od vojeno" it is giving me the 401 resposne.
I have tried all those ways.

$res = $client->get('/rest/api/2/group?groupname=od vojeno&expand=users');

$res = $client->get('/rest/api/2/group?groupname=od+vojeno&expand=users');

$res = $client->get('/rest/api/2/group?groupname=od%20vojeno&expand=users');

$res= $client->get('/rest/api/2/group?groupname=od%20vojeno&expand=users');

$client->get('/rest/api/2/group',[
                'query' => [
                    'groupname' => 'od vojeno',
                ],
            ]);
And all combinations with decoded/encoded parameter but cant make it run allways is 401 error

**Comment by brezzhnev** [comment]
The bug highly probable within signature creating logic, you can debug it there:
https://github.com/brezzhnev/atlassian-connect-core/blob/master/src/Helpers/JWTHelper.php#L116

Will take a look as well when will be able.

**Comment by brezzhnev** [comment]
Fixed in [v1.2.3](https://github.com/brezzhnev/atlassian-connect-core/releases/tag/v1.2.3).
